name: Python CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 black bandit pytype

    - name: Run Pylint
      run: pylint **/*.py
      if: ${{ always() }}

    - name: Run Flake8
      run: flake8 **/*.py
      if: ${{ always() }}

    - name: Run Black
      run: black --check **/*.py || black **/*.py
      if: ${{ always() }}

    - name: Run Bandit
      run: bandit -r .
      if: ${{ always() }}

    - name: Run Pytype
      run: pytype **/*.py
      if: ${{ always() }}
